In [1]:
import numpy as np
a = np.load('mi_all.npy')
print(a.shape)


(23, 2, 112, 4)


In [2]:
mi_xt_mean = np.mean(a,0)[0]
mi_ty_mean = np.mean(a,0)[1]
#mi_xt_mean = a[0,0,:,:]
#mi_ty_mean = a[0,1,:,:]
print(mi_xt_mean.shape)
print(mi_xt_mean)
print(mi_ty_mean)

(112, 4)
[[12.49101983 10.87400115  9.43937523  7.27206015]
 [12.51003195 11.16024147  9.26748507  7.41889326]
 [12.47128866 10.60563581  9.2890973   7.06295187]
 [12.54406232 10.73655932  9.41147584  6.90432211]
 [12.55691278 10.78242289  9.21195903  6.87019835]
 [12.48317249 10.91919704  9.19357717  6.78338919]
 [12.45360225 10.58865328  9.4828531   7.06651275]
 [12.439782   10.58104437  9.34438934  7.21556231]
 [12.42336846 10.67818117  9.21191974  7.19671639]
 [12.32132171 10.93739944  9.2599094   7.11898163]
 [12.38782041 10.48682006  9.24767342  7.26583378]
 [12.32984279 10.65209643  9.10225791  7.21565357]
 [12.30072459 10.75475039  9.16569849  7.16851759]
 [12.24196969 10.56402947  9.21585342  7.22639918]
 [12.3196908  10.48202017  9.24470063  7.22233392]
 [12.28006497 10.51994587  9.14947679  7.23828591]
 [12.21596717 10.37028982  9.11872028  7.1491521 ]
 [12.33190756 10.61425339  9.17835241  7.08346528]
 [12.26894897 10.55066267  9.22313007  7.17566422]
 [12.33360643 10.74787

In [3]:
IXM_N = mi_xt_mean[0,:]
IYM_N = mi_ty_mean[0,:]

T =1

for i in range(1,mi_xt_mean.shape[0]):
    
    A_ = i <= 4 and i % 1 == 0  
    A0 = i > 4 and i <= 10 and i % 2 == 0    
    A1 = i > 10 and i <= 30 and i % 3 == 0     
    A2 = i > 30 and i % 3 == 0    

    #if A0 or A1 or A2:
    if  A0 or A1 or A2:
        mean_vec_xt = np.mean(mi_xt_mean[T:i+1,:],axis=0)
        mean_vec_yt = np.mean(mi_ty_mean[T:i+1,:],axis=0)  
                             
        #print(T,i+1)                      
        IXM_N = np.append(IXM_N,mean_vec_xt)
        IYM_N = np.append(IYM_N,mean_vec_yt)
        
        T = i+1

        
IXM_N = np.reshape(IXM_N,(-1,4))
IYM_N = np.reshape(IYM_N,(-1,4))
print(IXM_N.shape)

(38, 4)


In [19]:
print(a[-2,1,-1,-1])

3.2498646359407926


In [7]:
#mi_ty_mean[0:10,3]=np.array(mi_ty_mean[0:10,3])
IXM_N, IYM_N = mi_ty_mean, mi_ty_mean
print(IXM_N.shape)
print(IYM_N.shape)

(127, 4)
(127, 4)


In [3]:
import pandas as pd
T=3
IXM_N, IYM_N = np.zeros((mi_xt_mean.shape[0]-T+1,4)), np.zeros((mi_ty_mean.shape[0]-T+1,4))

for i in range(4):
    IXM_N[:,i]=pd.rolling_mean(mi_xt_mean[:,i],T)[T-1:]
    IYM_N[:,i]=pd.rolling_mean(mi_ty_mean[:,i],T)[T-1:]
    
print(IXM_N.shape)
print(IYM_N.shape)

(17, 4)
(17, 4)


/Users/morteza/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: pd.rolling_mean is deprecated for ndarrays and will be removed in a future version
  
/Users/morteza/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: FutureWarning: pd.rolling_mean is deprecated for ndarrays and will be removed in a future version
  import sys


In [4]:
# Plot like Tishby

#matplotlib inline
import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
sns.set_style('darkgrid')


plt.figure(figsize=(8,8))
gs = gridspec.GridSpec(4,2)
#for actndx, (activation, vals) in enumerate(measures.items()):
#    epochs = sorted(vals.keys())
#    if not len(epochs):
#        continue

COLORBAR_MAX_EPOCHS=15000

plt.tight_layout()        

fig=plt.figure(figsize=(10,5))

#max_epoch = max( (max(vals.keys()) if len(vals) else 0) for vals in measures.values())
sm = plt.cm.ScalarMappable(cmap='gnuplot', norm=plt.Normalize(vmin=0, vmax=COLORBAR_MAX_EPOCHS))
sm._A = []

#fig=plt.figure(figsize=(10,5))
#for actndx, (activation, vals) in enumerate(measures.items()):
#    epochs = sorted(vals.keys())
#    if not len(epochs):
#        continue
#    plt.subplot(1,2,actndx+1)    
    
    
#n_epoch = mi_xt_mean.shape[0]
n_epoch = IXM_N.shape[0]

PLOT_LAYERS = [0]
for epoch in range(0,n_epoch):
    c = sm.to_rgba(220*(epoch))
    #xmvals = np.array(vals[epoch]['MI_XM'])[PLOT_LAYERS]
    #ymvals = np.array(vals[epoch]['MI_YM'])[PLOT_LAYERS]

    #xmvals = mi_xt_mean[epoch] 
    #ymvals = mi_ty_mean[epoch]
    xmvals = IXM_N[epoch] 
    ymvals = IYM_N[epoch]
    
    plt.plot(xmvals, ymvals, c=c, alpha=0.1, zorder=1)
    plt.scatter(xmvals, ymvals, s=40, facecolors=[c for _ in PLOT_LAYERS], edgecolor='none', zorder=2)
    
plt.ylim([1, 3.5])
plt.xlim([4, 14])
plt.xlabel('I(X;M)')
plt.ylabel('I(Y;M)')
plt.title('Tanh')
    
# colorbar
  
#cbaxes = fig.add_axes([1.0, 0.125, 0.03, 0.8]) 
#plt.colorbar(sm, label='Epoch', cax=cbaxes)
plt.colorbar(sm, label='Epoch')


plt.tight_layout()

plt.show()